name: Web App

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  deploy-web:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Setup Node
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    # Build Web
    - name: Install Web App Dependencies
      run: |
        cd web/
        npm i
    - name: Build Web App
      run: |
        cd web/
        npm run build

    # Deploy Web
    - name: Publish Docs
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: web/build/
